FROM php:7.3.6-fpm-alpine3.9 as builder


RUN apk add --no-cache shadow openssl bash mysql-client nodejs npm
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www
RUN rm -rf /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /var/www

RUN composer install && \
    php artisan cache:clear && \
    chmod -R 775 storage

RUN ln -s public

EXPOSE 9000
ENTRYPOINT [ "php-fpm" ]
